Dockerfile

Update Dockerfile to comply with GitHub Actions [guidelines](https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions)
Tested locally with `podman`
```
podman build -f Dockerfile -t localhost:5000/trestlebot:latest
podman run -e "BRANCH=test" -v <path_to_git_repo>:/data -w /data localhost:5000/trestlebot:latest
```

chore: updates Dockerfile to comply with GitHub actions guidelines

---

tests/trestlebot/test_cli.py
trestlebot/bot.py
trestlebot/cli.py
trestlebot/log.py
trestlebot/tasks/authored/catalog.py
trestlebot/tasks/authored/compdef.py
trestlebot/tasks/authored/profile.py
trestlebot/tasks/authored/ssp.py

This adds  the logger from compliance-trestle with a small change to the logger's name. 
N/A

Adds logger

---

action.yml
entrypoint.sh
trestlebot/bot.py
trestlebot/cli.py

Allow for custom PR titles through the Github Action

feat: allows pull request title to be configurable

---

tests/trestlebot/tasks/authored/test_profile.py
trestlebot/tasks/authored/compdef.py
trestlebot/tasks/authored/profile.py

Refs: PSCE-173
Adds logic to created default profile as a utility function in trestlebot. Related to #22.

PSCE-173 - feat: adds create default profile logic to AuthoredProfile type

---

.github/workflows/ci.yml
.github/workflows/codecov.yml
Makefile
poetry.lock
pyproject.toml
tests/trestlebot/tasks/test_assemble_task.py
tests/trestlebot/tasks/test_regenerate_task .py
tests/trestlebot/test_bot.py
trestlebot/bot.py

Adds checks for code coverage
Adds safety and bandit checks
Adds unit tests to tasks and bot
N/A

chore: test code cov

---

action.yml
entrypoint.sh
tests/trestlebot/test_bot.py
trestlebot/bot.py
trestlebot/cli.py

Adds the pull request number as an output of the action for further steps in workflow to facilitate automation like assigning reviewers or making comments.

feat: add pr_number as an optional output on the action

---

trestlebot/tasks/authored/types.py

Fixes `invalid author type` when using trestlebot for ssp autofix
- Manual test completed

fix: updates comparison for ssp type in get_trestle_model_dir

---

.github/workflows/publish.yml

Update the publish workflow to push to quay
https://github.com/jpower432/trestle-bot/actions/runs/5832422787

chore: update publish to push to quay.io

---

action.yml
tests/trestlebot/tasks/test_assemble_task.py
tests/trestlebot/tasks/test_regenerate_task .py
trestlebot/cli.py
trestlebot/tasks/assemble_task.py
trestlebot/tasks/base_task.py
trestlebot/tasks/regenerate_task.py

Update the skip_items like to accept glob patterns instead of an exact match the each directory name.
Fixes PSCE-222

PSCE-222 - feat: updates skip_items to accept glob patterns

---

Makefile
poetry.lock
pyproject.toml
tests/data/yaml/test_complete_rule.yaml
tests/data/yaml/test_complete_rule_no_params.yaml
tests/data/yaml/test_incomplete_rule.yaml
tests/testutils.py
tests/trestlebot/tasks/test_rule_transform_task.py
tests/trestlebot/test_cli.py
tests/trestlebot/transformers/__init__.py
tests/trestlebot/transformers/test_yaml_to_csv.py
trestlebot/const.py
trestlebot/tasks/assemble_task.py
trestlebot/tasks/base_task.py
trestlebot/tasks/regenerate_task.py
trestlebot/tasks/rule_transform_task.py
trestlebot/transformers/__init__.py
trestlebot/transformers/trestle_rule.py
trestlebot/transformers/yaml_to_csv.py

PSCE-237 - Adds Rule YAML to CSV transformation

---

.github/workflows/ci.yml
.github/workflows/codecov.yml
.pre-commit-config.yaml
Makefile
poetry.lock
pyproject.toml

Adds semgrep check as a pre-commit and in CI to run the bandit ruleset and python ruleset.

chore: adds semgrep pre-commit and CI action

---

tests/trestlebot/transformers/test_validations.py
tests/trestlebot/transformers/test_yaml_transformer.py
trestlebot/tasks/rule_transform_task.py
trestlebot/transformers/csv_transformer.py
trestlebot/transformers/validations.py
trestlebot/transformers/yaml_transformer.py

Adds basic validation implementation which allows for additional validation on top of pydantic.
- The added validation currently checks that the parameter and alternatives values are structured correctly
- Check that the profiles referenced are accessible.
Blocked #50

PSCE-239: feat: adds validation for YAML trestle rules

---

tests/data/yaml/test_complete_rule_no_params.yaml
tests/trestlebot/tasks/test_rule_transform_task.py
trestlebot/transformers/csv_transformer.py
trestlebot/transformers/trestle_rule.py

The csv_to_oscal_cd task skips the first two rows. The output CSV only had a header row so the first rule was always skipped. This change adds an example row to where the descriptions would be.
Blocked by #55

fix: adds an example row to final CSV to account for skipped rows

---

actions/autosync/action.yml
actions/autosync/auto-sync-entrypoint.sh
actions/rules-transform/action.yml
actions/rules-transform/rules-transform-entrypoint.sh
trestlebot/bot.py
trestlebot/entrypoints/autosync.py
trestlebot/entrypoints/entrypoint_base.py
trestlebot/entrypoints/log.py
trestlebot/entrypoints/rule_transform.py

Adds proper configuration of trestlebot logger along with compliance-trestle logger
Allows verbosity to be set from the actions files
Related: PSCE-256

feat: configure logger for module and control from actions files

---

CONTRIBUTING.md
Makefile
poetry.lock
pyproject.toml
tests/e2e/Dockerfile
tests/e2e/README.md
tests/e2e/mappings/mapping.json
tests/e2e/play-kube.yml
tests/e2e/test_e2e.py
tests/testutils.py
tests/trestlebot/entrypoints/test_autosync.py

Adds end to end tests that can be run locally to verify trestle-bot functions as expected in the container.
- Adds a mock api to provide static responses for git client using WireMock
- Adds container images build and removal fixture
- Adds initial command test case and response
N/A - Only tests were added
Run `make test-e2e` or `make test-slow` to run all tests.

PSCE-263: tests: adds initial end to end test for rules transform

---

tests/trestlebot/tasks/test_assemble_task.py
tests/trestlebot/tasks/test_base_task.py
tests/trestlebot/tasks/test_regenerate_task.py
trestlebot/entrypoints/autosync.py
trestlebot/entrypoints/rule_transform.py

Fixes regression found because of the way ModelFilter is initialized in autosync and rules-transform.
- https://github.com/jpower432/cautious-potato/actions/runs/6658999116/job/18097116290
- https://github.com/jpower432/cautious-potato/actions/runs/6658923736

fix(entrypoint): fixes top level ModelFilter logic

---

tests/e2e/README.md
tests/e2e/test_e2e.py
trestlebot/const.py

Add e2e scenario for testing create-cd in a containerized environment.
- Adds the new command test with multiple scenarios
- Adds additional validations to both E2E tests
- Add the ability to skip image building if the image is available.

test: add e2e scenarios for create-cd

---

actions/README.md
actions/autosync/README.md

Adds example workflow to `actions` documentation to show how output for can used with other actions. In this case, `actions/labeler`. Also adds examples for how to use the actions together for component definition management.
N/A - Docs add

docs(actions): adds examples with outputs to actions documentation

---

.github/workflows/ci.yml
.github/workflows/codecov.yml
sonar-project.properties
trestlebot/entrypoints/autosync.py

https://sonarcloud.io/summary/overall?id=rh-psce_trestle-bot

task(ci): add sonar

---

trestlebot/entrypoints/entrypoint_base.py
trestlebot/transformers/base_transformer.py
trestlebot/transformers/validations.py

Removes TODO comments. We should capture these in issues if needed.
Triggered by #77 
N/A

chore: removes todo comments

---

tests/trestlebot/test_bot.py
trestlebot/bot.py
trestlebot/entrypoints/entrypoint_base.py

Refactors bot.py to reduce cognitive complexity.
Triggered by #77 
- https://github.com/jpower432/cautious-potato/actions/runs/6788464720/job/18453540410
- https://github.com/jpower432/cautious-potato/actions/runs/6788556775/job/18453820537
- https://github.com/jpower432/cautious-potato/actions/runs/6788556785/job/18453820562

refactor(bot): refactor bot.py logic into TrestleBot class

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Add dev container configuration and Containerfile.
> Due to the need to elevate privileges when running `podman` in container, this currently does not include support for running the E2E tests with the environment.

feat: adds dev container configuration files

---

.github/workflows/e2e.yml
.github/workflows/publish.yml
tests/conftest.py
tests/e2e/README.md
tests/e2e/test_e2e_compdef.py
tests/e2e/test_e2e_ssp.py
tests/testutils.py

- Pre-push image scanning
- Adds optional E2E tests to run after push. Enabled by default with the `workflow_dispatch` trigger.
The workflow dispatch trigger is used on the `publish.yml` to allow for changes to be validated in the published image.
E2E tests can be run as the first step to check for regressions before conducting further validation. 
Blocked by #91 
Blocked by #87

feat: adds image tests to CI

---

tests/trestlebot/tasks/test_assemble_task.py
tests/trestlebot/tasks/test_regenerate_task.py
trestlebot/tasks/assemble_task.py

- Adds tests to `test_assemble_task.py` and `test_regenerate_task.py` for failure/negative testing.
- Add check and test to ensure the markdown directory exists in the assemble task
Stacked/Incorporates #98 in response to PR feedback.

test: adds negative tests to assemble and regenerate task tests

---

.github/workflows/publish.yml

Make the using cache optional when using `workflow dispatch` and disable the use of it when creating the releases to ensure the we don't experience stale builds or miss out on required updates.

ci: allows no-cache option for image building to ensure updated deps

---

.github/workflows/publish.yml

Metadata pulled into the virtual environment during a fresh image build for
dependencies contain false positives/examples in docs that are flagged. 
Skip Python metadata in directories that are not maintained in this project.

chore: adds skip-dirs to trivy image scan

---

.github/workflows/publish.yml

Adds image signing with `cosign` to the image publishing workflow.
Stacked with #116 to resolve issues with image published.
https://github.com/jpower432/trestle-bot/actions/runs/7197914376

chore: adds image signing with cosign to publish.yml

---

tests/trestlebot/entrypoints/test_entrypoint_base.py

Adds unit test coverage for `set_git_provider` method on `EntrypointBase` class

test: adds unit tests for the set_git_provider method for EntrypointBase

---

tests/trestlebot/entrypoints/test_autosync.py
tests/trestlebot/entrypoints/test_entrypoint_base.py
tests/trestlebot/tasks/authored/test_types.py
trestlebot/entrypoints/autosync.py
trestlebot/tasks/authored/types.py

Identified missed paths on new code in SonarClould [report](https://sonarcloud.io/component_measures?id=rh-psce_trestle-bot&metric=new_coverage&view=list).
This PR adds tests to covered those missed paths.
N/A

test: add unit tests for missed code paths

---

.pre-commit-config.yaml

Bug found when changes to a python file are made. The language on the local pre-commit should be `system` not `script`.
Checked with a commit that modified a python file.

fix: updates language for linting pre-commit to system

---

CONTRIBUTING.md

There is a broken link and the information about how the linting checks could be run are unclear.
Docs Only

docs: updates CONTRIBUTING.md with minor fixes

---

.devcontainer/Dockerfile
.github/actions/setup-poetry/action.yml
Dockerfile
Makefile

Updates poetry from 1.5.1 to 1.7.1
- Tested with Codespaces
- Tested image E2E/CI - https://github.com/jpower432/trestle-bot/actions/runs/7401558662/job/20137879875

chore(deps): bumps the default poetry version used in image and the environment to 1.7.1

---

poetry.lock
pyproject.toml

Update `compliance-trestle` to version 2.5.0

chore(deps): bump compliance-trestle to version 2.5.0

---

CONTRIBUTING.md
Makefile
actions/autosync/README.md
actions/create-cd/README.md
actions/rules-transform/README.md
scripts/update_action_readmes.py

- Adds automation script for updating Markdown tables in Action README files
- Adds docs updates generated from the script
- Adds instructions on use in `CONTRIBUTING.md`
We need to sync specific information from the `action.yml` to the corresponding README.md files and this type of information is tedious to update and can get out of date very easily. This is a script that will  manage blocks in each of the README.md with information from the `action.yml` file. As specified in the linked issue, reading a Markdown table is more straightforward than the YAML.
Fixes #89 
**Not end-user facing feature**
1. Update the description in one of the actions files
2. Run
```
make update-actions-readmes
```
3. Review the table updates

chore: adds automation to update action README.md files

---

tests/conftest.py
tests/data/json/invalid_comp.json
tests/e2e/test_e2e_compdef.py
tests/e2e/test_e2e_ssp.py
tests/trestlebot/entrypoints/test_autosync.py
tests/trestlebot/tasks/test_sync_upstream_task.py
trestlebot/tasks/authored/base_authored.py
trestlebot/tasks/sync_upstreams_task.py

A `SyncUpstreams` Task to sync third party content/artifact dependencies in a trestle workspace to a local trestle workspace.
Recommended to review each commit separately.
The first two commits have preparatory changes to reduce technical debt/code duplication that would be proliferated by this feature.
We need automation that will keep our third party content update to date that works across CI providers. We have a [bash script](https://github.com/RedHatProductSecurity/oscal-component-definitions/blob/main/scripts/update-from-upstream.sh) currently performing this in one location.
This is a basic implementation for a "trestle aware" copy from upstream repository.
For future iterations, the goal is to start simple and built a task that can extend to different types of sources (i.e. …

PSCE-302 feat: adds a task to sync third party content to a local trestle workspace

---

tests/trestlebot/tasks/authored/test_ssp.py
trestlebot/tasks/authored/ssp.py

Removing unused portions of this function.
The SSP filter functionality is meant for reporting purposes and not for editing currently.

chore: removes markdown creation from create_new_with_filter

---

tests/data/json/invalid_test_ssp_index.json
tests/data/json/test_ssp_index.json
tests/data/yaml/extra_yaml_header.yaml
tests/testutils.py
tests/trestlebot/tasks/authored/test_ssp.py
tests/trestlebot/tasks/authored/test_types.py
tests/trestlebot/tasks/test_assemble_task.py
tests/trestlebot/tasks/test_regenerate_task.py
trestlebot/const.py
trestlebot/tasks/authored/ssp.py

Adds YAML header to the SSPIndex to use custom YAML headers with `ssp-generate`
Refactors the way ssp index writing is done in the unit test to prepare for this. Having another util function to write the index essentially does what the `SSPIndex` class does. To reduce the changes every time that class is change, using it to create ssp index files dynamically and using test data for other tests.

PSCE-321-P1: Adds yaml header path to ssp index

---

CONTRIBUTING.md
pyproject.toml
tests/conftest.py
tests/e2e/test_e2e_compdef.py
tests/e2e/test_e2e_ssp.py
tests/testutils.py
tests/trestlebot/entrypoints/test_create_ssp.py
tests/trestlebot/entrypoints/test_sync_upstreams.py
tests/trestlebot/tasks/authored/test_ssp.py
tests/trestlebot/test_bot.py
tests/trestlebot/test_github.py
tests/trestlebot/test_gitlab.py
trestlebot/entrypoints/create_ssp.py
trestlebot/tasks/authored/ssp.py

Adds a create-ssp entrypoint for SSP bootstrapping 
Stacked with #157 
SSP creation is becoming more customized with
the addition of yaml header. Adding a `create-ssp` entrypoint will reduce error  when working with autosync command and SSPs.

PSCE-299: Adds create-ssp entrypoint

---

tests/trestlebot/tasks/authored/test_ssp.py
trestlebot/tasks/authored/ssp.py

The main component is needed in a trestle SSP for it be valid. This has been added by default when filtering by components in workspace component definitions and option added to filter out all component but the main.

feat: adds main_comp_only to create_new_with_filter in ssp.py

---

tests/conftest.py
tests/data/yaml/test_complete_rule_multiple_controls.yaml
tests/testutils.py
tests/trestlebot/tasks/test_rule_transform_task.py
tests/trestlebot/transformers/test_csv_transformer.py
trestlebot/transformers/csv_transformer.py

Updates the CSVTransformer class to separate control with spaces and not commas. This is what is expected by the trestle CSV to OSCAL cd task.
Fixes #182

fix: updates CSVTransformer to separate controls with spaces instead of commas

---

tests/conftest.py
tests/e2e/conftest.py
tests/e2e/e2e_testutils.py
tests/e2e/test_e2e_compdef.py
tests/e2e/test_e2e_ssp.py
tests/testutils.py
tests/trestlebot/entrypoints/test_create_cd.py

Update E2E test code to use a single class and fixture instead of a collection of functions.
Also removes negative test cases (which test specific failures and logging statements) that don't need to be tested in the container to the unit tests from the e2e tests.
Fixes #166

refactor: adds a E2ETestRunner for E2E tests

---

actions/common.sh

The input repository should always exist in the GitHub workspace. Setting it again in the entrypoint is redundant.

chore: removes input repository from the safe workspace

---

actions/autosync/README.md
actions/autosync/action.yml

Removes default version from `autosync` GitHub Action. Default behavior should be to not modify the version value
Fixes #193 
Result - https://github.com/jpower432/trestlebot-demo-cd/commit/5d1fd30bd341cd65d71f00a4aba776685e5d8404

fix: removes default version in GitHub action

---

trestlebot/entrypoints/log.py
trestlebot/tasks/assemble_task.py
trestlebot/tasks/regenerate_task.py
trestlebot/tasks/rule_transform_task.py

Fixes info logs ensure the output in the default mode looks cohesive with the `trestle` logs
Incorporated in #195

chore: update logging format

---

actions/README.md

Updates `Add New Action` documentation that had incorrect paths and incomplete steps.
N/A

docs: update README under actions directory

---

Makefile
tests/testutils.py
tests/trestlebot/entrypoints/test_autosync.py
tests/trestlebot/entrypoints/test_create_cd.py
tests/trestlebot/entrypoints/test_create_ssp.py
tests/trestlebot/entrypoints/test_sync_upstreams.py
trestlebot/entrypoints/log.py

GitLab CI still logs extra messages with log filtering. Disabling propagation to isolate the trestlbot logger similar to the `compliance-trestle` logger.
Add a fix in tests to ensure logs are still found using `caplog` during test time

fix: prevent extra log messages in stdout

---

Makefile
tests/e2e/e2e_testutils.py
tests/e2e/test_e2e_compdef.py
tests/e2e/test_e2e_ssp.py

- Improve readability of `test_e2e_ssp.py`
- Remove missed `subprocess` line
- Checks output on intentional E2E failures

refactor: improves readability of the SSP end to end tests

---

tests/trestlebot/test_gitlab.py
trestlebot/github.py
trestlebot/gitlab.py
trestlebot/provider.py

In `GitProvider` class and concrete implementations, move any repo url string parsing to `urllib` and only use regex for path pattern matching and capturing. Also removes `regex` related code smell.
Prep for #200

PSCE-408 refactor: replaces regex with urllib for repo URL parsing

---

poetry.lock
pyproject.toml
tests/testutils.py
trestlebot/tasks/authored/catalog.py
trestlebot/tasks/authored/profile.py

There are currently string type parameters within in the catalog and profile tasks codebase that have default values of empty string ("").  This is causing an exception to be thrown within compliance-trestle when performing a `if is None` check to determine if the parameter has been set.    To avoid this issue, the default values should be set to `None` instead of empty string.  An issue will also be created in compliance-trestle to address the root cause.
Fixes [Issue-230](https://github.com/RedHatProductSecurity/trestle-bot/issues/230)

[Issue-230] Set default values to None instead of empty strings

---

.github/actions/e2e-testing/action.yml
.github/actions/publish-image/action.yml
.github/actions/setup-poetry/action.yml
.github/workflows/ci.yml
.github/workflows/codecov.yml
.github/workflows/publish.yml

Pinning GitHub Actions to a commit-sha is a safer practice and supported by Dependabot for continuous updates
- Demonstrated `ci.yml` with this PR
- Publish -  https://github.com/jpower432/trestle-bot/actions/runs/9422275168/job/25958179482
- Hardware:
- Toolchain:
- SDK:

ci: pins all reference GitHub actions to a hash value

---

.github/workflows/ci.yml
.github/workflows/publish.yml
tests/conftest.py
tests/e2e/e2e_testutils.py
tests/trestlebot/tasks/test_sync_upstream_task.py
tests/trestlebot/test_github.py
tests/trestlebot/test_gitlab.py

Changes
- Ubuntu 24.04 has version 4 of `podman` which is compatible with version of Docker (*Note* - this public [beta](https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/) slated to go GA in [Sept](https://github.com/github/roadmap/issues/980))
- v4 of podman has a default restart policy of always which cause unexpected behavior during tests (follow-on issue will be needed for this).
Why use `podman` and `docker`?
They are used in different contexts. `podman` is used to manage containers in E2E testing. `docker` GitHub Actions are used for image building in the release pipeline.
- Using `podman` pods is required to run the mock server and trestle-bot on the same network stack. It is also what the team is more familiar with.
- In …

fix: updates GitHub Actions runner image and restart policy

---

.github/dependabot.yml

Reduces `dependabot` run frequency from daily to weekly.  This allows for a more manageable rate of PRs to address version updates.
Fixes [Issue #285](https://github.com/RedHatProductSecurity/trestle-bot/issues/285)

chore: change dependabot frequency to weekly

---

.github/dependabot.yml

Updates the dependabot prefix to ensure the PR title are using Conventional Commits
Fixes #306 
N/A

fix: updates dependabot prefix for conventional commits

---

.github/workflows/mkdocs.yml
docs/index.md
mkdocs.yml
poetry.lock
pyproject.toml

Adding initial [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) files for repo documentation.  The mkdocs content will be published to Github pages.  Future pull requests will update and create the Markdown content for publishing.

docs: initialize mkdocs config and workflow for github pages

---

trestlebot/__main__.py

This PR changes the default trestlebot module behavior to invoke the `init` entrypoint instead of the `autosync` entrypoint.

feat: update module default to use init entrypoint

---

.github/workflows/mkdocs.yml
poetry.lock
pyproject.toml

Adds the `markdown-include` package to the `publish-docs` GitHub workflow and poetry dev group.
Fixes https://github.com/RedHatProductSecurity/trestle-bot/issues/338

fix: add markdown-include package to workflow and poetry

---

.github/actions/publish-image/action.yml
.github/workflows/publish.yml

When rebuilding old images, we need to run the E2E from that references to avoid issues with breaking changes in the CLI. This solution checks out the git repository at the references determined by the trigger and uses the Docker `build-push` action with a path context.
Fixes #332

fix: updates e2e tests checkout ref during image publishing

---

Makefile
tests/trestlebot/test_bot.py
trestlebot/bot.py

The changes made allow the body of the pull request submitted by trestle-bot to be configured as "Authored by trestle-bot." The changed parameter allows for configuring the PR submitted by trestle-bot to provide additional context for the user. The Makefile develop test case change allows for proper local working privileges. 
Closes #320
- Firmware version: N/A
- Toolchain: N/A
- SDK: N/A

feat(bot): change for configuring trestle-bot PR body update

---

docs/tutorials/github.md

Edited GitHub Tutorial for required command changes, clarity, and formalizing of language.
Ran through tutorial on a Fedora Linux 39 workstation
- Firmware version: n/a
- Hardware: Lenovo Thinkpad T580
- Toolchain: n/a
- SDK: n/a

docs: updates after user testing to github.md

---

TEMPLATES/github/trestlebot-rules-transform.yml

Fixes an issue where the paths-filter job fails after the first run

fix: run the paths-filter step in its own job

---

CONTRIBUTING.md

The changes made to the `CONTRIBUTING.md` guide include a section on "Authoring CI Workflows." The changes outline the importance of using third party actions pinned to hash values for secure maintenance of dependencies and version updates. The changes made highlight the pin generation syntax that references the full length commit SHA associated with the version of the action within the action's repository.
Fixes #317
- Firmware version: N40ET47W (1.29)
- Toolchain:
- SDK:

docs: authoring CI workflows for trestle-bot section in contributing guide

---

trestlebot/tasks/sync_cac_content_task.py

Refactor function for create or update component definition

chore: split create or update component definition function

---

README.md
docs/tutorials/sync-cac-content.md

Add the document for the CLI `sync-cac-content`.
- Hardware:
- Toolchain:
- SDK:

docs: CPLYTM-498 add document for sync-cac-content

---

trestlebot/bot.py

Fixes CPLYTM-516,  Trestle-bot Error: list index out of range

fix: CPLYTM-516 list index out of range error

---

.github/workflows/codecov.yml
tests/data/json/rhel8.json
tests/testutils.py
tests/trestlebot/cli/test_sync_oscal_content_cmd.py
trestlebot/cli/commands/sync_oscal_content.py
trestlebot/cli/root.py
trestlebot/tasks/sync_oscal_content_task.py
trestlebot/utils.py

Introduce sync-oscal-content cmd, sync OSCAL component definition information to cac, implemented parameters validation and sync.
Sample cmd:
```shell
poetry run trestlebot sync-oscal-content cac-control --branch main --cac-content-root ~/content --committer-name axuan --committer-email axuan@redhat.com --dry-run --repo-path ~/trestlebot-workspace --product ocp4
```
Fixes CPLYTM-544
- Hardware:
- Toolchain:
- SDK:

feat: Introduce sync-oscal-content cmd, implemented parameters validation and sync

---

docs/tutorials/sync-cac-content.md
tests/trestlebot/cli/test_sync_cac_content_cmd.py
trestlebot/cli/commands/sync_cac_content.py

This PR updates the `sync-cac-content component-definition` command to resolve cac profiles from the `--cac-profile` flag when authoring OSCAL Component Definitions. The `--cac-profile` name will now be joined with the `--cac-content-root` and `--product` for accessing the CaC profile associated with the specified product.  This fixes the need for supplying a path to the `--cac-profile` flag and now only requires the profile name. The `--cac-profile` option will still functionally allow for use of the path, but it is not required. 
Fixes #563
- **The command used for testing:**
```
poetry run trestlebot sync-cac-content component-definition --product rhel9
--cac-content-root ~/CaC/forked_content/content --cac-profile anssi_bp28_intermediary
--repo-path ~/demos/tmp-trestle-demos …
```

fix: CPLYTM-563: profile path resolved from cac profile name

---

trestlebot/tasks/sync_cac_content_task.py

This PR addresses CPLYTM-567: resolving controls from real profiles for transformation of component definitions. The initial issue occurred when the product `profile.yml` selections field indicated "all" levels to be extracted from the associated `policy_id` control file. 
This update excludes the explicit use of "all" levels and provides a more generic approach for accessing the specified levels of the `policy_id`. The policy_id and level associated with the product `profile.yml` will be leveraged to transform real profiles to component definitions. 
**The `sync_cac_content_task` will now:** 
1. Read and extract the `policy_id: level` from selections in the product profile.yml.
2. Capture controls from the control file associated with the selected level. 
3. Then, include those controls …

fix:  CPLYTM-567 updates for real profile component definition transformation

---

trestlebot/tasks/sync_cac_catalog_task.py

There is an existing bug in which the description from the CaC control is not being populated within the `Control Statement` of the control in the OSCAL catalog.  This PR solves the issue by adding the description as the prose in the control parts.
Fixes CPLYTM-632
The fix can be verified by running the `trestlebot sync-cac-content catalog` command to create a catalog from a CaC control file.  Then observing the `prose` field in the control parts.  Example:
```
"parts": [
{
"id": "r80_smt",
"name": "statement",
"prose": "All network services must be listening on the correct network intefaces."
}
]
```

fix: CPLYTM-632 use description from cac profile as prose

---

docs/tutorials/sync-oscal-content.md
tests/trestlebot/cli/test_sync_oscal_content_cmd.py
trestlebot/tasks/sync_oscal_content_task.py
trestlebot/utils.py

Improvement for sync-oscal-content command, Add comment to corresponding control when find missing rule.
Fixes CPLYTM-608,CPLYTM-609
Example of add comment to control file if rule not exist.
If rules field is empty:
If rules is not empty:
- Hardware:
- Toolchain:
- SDK:

feat: Add comment to corresponding control when find missing rule

---

docs/tutorials/sync-oscal-content.md
tests/data/json/rhel8.json
tests/trestlebot/cli/test_sync_oscal_content_cmd.py
trestlebot/tasks/sync_oscal_content_task.py
trestlebot/utils.py

Improvement for `sync-oscal-content cac-control` command.Create non-exist variables value in cac content var file when sync OSCAL component definition.
Fixes CPLYTM-656
- Hardware:
- Toolchain:
- SDK:

feat: CPLYTM-656 CPLYTM-655 Create non-exist variables value in cac side when sync OSCAL CD

---

poetry.lock
pyproject.toml

PR to update trestle version from `3.8.0` to `3.8.1`.  This also bumps the jinja dependency to `3.1.6` which addresses the moderate security findings [here](https://github.com/complytime/trestle-bot/security/dependabot).

chore: update trestle version to 3.8.1

---

scripts/get_mappings_profile_control_levels.py
scripts/get_product_controls.py
trestlebot/tasks/sync_cac_content_task.py
trestlebot/utils.py

Description:
This module is designed to handle the mapping of CAC profile names, their corresponding available control files, and the selected security levels. It is useful to determine which profiles are mapped when detecting updates of CAC control files. We could update the related component definition according to the mapped profiles.
The output is a dictionary containing information about the profile, policy ID, and the associated security levels.
How to use it:
python get_mappings_profile_control_levels.py "product" "content_root_dir"
E.g., $`python get_mappings_profile_control_levels.py "rhel10" "/path/of/cac-content"`
Output Format:
The module produces an output dictionary with the following structure:
{
'profile_name': 'stig',  
'policy_id': 'stig_rhel9',
'levels': ['high', …

feat: [CPLYTM-627] get mapping of profile and available control

---

.github/workflows/publish.yml

Using the gh CLI requires the repository to already be cloned. The publish.yml clones the repository based on input, so the latest release is updated to pull the information in a way that does not require a local copy of the repo.

fix: updates logic to get release information

---

trestlebot/tasks/sync_cac_content_task.py

This PR proposes a minor update to the logger statements that are returned for `--debug` for the `sync_cac_content component-definition` command. The update will provide the location and product name where transformed OSCAL Component Definitions have been updated or created in the trestlebot workspace. 
CPLYTM-710
Depends on #532 
```bash
poetry run trestlebot sync-cac-content component-definition --product rhel9 --cac-content-root ~/CaC/forked_content/content --cac-profile anssi_bp28_high --repo-path ~/demos/tmp-trestle-demos --oscal-profile anssi-high --component-definition-type software --committer-name hbraswelrh --committer-email test@redhat.com --branch main --dry-run
```
- Firmware version: N40ET47W (1.29 )
- Toolchain: …

fix: CPLYTM-710 updating logger statements

---

scripts/get_rule_impacted_files.py

This module is designed to get the controls and profiles that are impacted by
the updated rule. It is useful to determine how to sync the updated rule
to OSCAL component-definition.
How to run it:
`python get_rule_impacted_files.py rhel8 "/Users/huiwang/huiwang-fork/cac-content" dconf_db_up_to_date control`
It will list the impacted controls.
- Hardware:
- Toolchain:
- SDK:

chore: get profiles and controls are impacted by a rule

---

trestlebot/tasks/sync_cac_catalog_task.py

Update the `sync_cac_content` catalog task to ensure the output is OSCAL schema compliant.
```bash
poetry run trestlebot sync-cac-content catalog --dry-run --repo-path ~/trestlebot-workspace --committer-email test@redhat.com --committer-name test --branch main --cac-content-root ~/content --oscal-catalog anssi --cac-policy-id anssi
```

fix: CPLYTM-740 updates sync_cac_content_catalog task to set empty values to None

---

scripts/get_rule_impacted_files.py

This script filters the related controls and profiles of the updated rules and variables.  In the impacted controls, the SRG* controls could be ignored safely. To improve the efficiency of the CI sync-cac-oscal workflow, this PR would like to remove the SRG* controls.
`python scripts/get_rule_impacted_files.py rhel9 "/Users/huiwang/huiwang-fork/cac-content" "dconf_db_up_to_date" control`
Original output as follows:
`ccn_ol9 cis_rhel10 stig_ol9 stig_rhel9 ccn_rhel9 cis_almalinux9 cis_rhel9 cis_sle15 hipaa pcidss_3 SRG-OS-000480-GPOS-00227 cis_rhel8 cis_sle12 pcidss_4`
The new output looks as follows:
`hipaa cis_almalinux9 ccn_rhel9 cis_sle15 cis_rhel8 cis_sle12 ccn_ol9 cis_rhel10 pcidss_3 pcidss_4 cis_rhel9 stig_ol9 stig_rhel9`
- …

chore: remove the ignored SRG controls

---

tests/trestlebot/cli/test_sync_oscal_content_cmd.py
trestlebot/cli/commands/sync_oscal_content.py
trestlebot/tasks/sync_oscal_content_catalog_task.py

Introduce catalog subcommand for sync-oscal-content, this PR only introduce new command, implementation will in other PR.
`poetry run trestlebot sync-oscal-content catalog --cac-policy-id nist_ocp4 --cac-content-root ~/content --repo-path ~/trestlebot-workspace --committer-name test --committer-email test@redhat.com --branch main --dry-run`
- Hardware:
- Toolchain:
- SDK:

feat: CPLYTM-753 Introduce catalog subcommand for sync-oscal-content

---

tests/testutils.py
tests/trestlebot/cli/test_sync_oscal_content_cmd.py
trestlebot/tasks/sync_oscal_content_catalog_task.py

Implement sync-oscal-content catalog command
- Closes CPLYTM-754
On OSCAL side, `parts` field corresponding to CaC control file control `description` field, part named `statement` contains full data from  CaC `description` field, and part named `guidance` contains data begin with `Supplemental Guidance:` from  CaC `description` field.
Modify catalog control `parts` field in trestle workplace, then run command `poetry run trestlebot sync-oscal-content catalog --cac-policy-id nist_ocp4  --cac-content-root ~/content --repo-path ~/trestlebot-workspace --committer-name test --committer-email test@redhat.com --branch main --dry-run`. After that, check corresponding change in CaC side(control description field in control file).

feat: CPLYTM-754 Implement sync-oscal-content catalog command

---

.github/workflows/release.yml

Currently we have a release cadence of about three weeks and in the meantime it is not necessary to keep a release PR open consuming CI resources whenever a PR is merged into main. When we are closer to a release, we can manually trigger this workflow. This will also allow CI tests to be executed on it.
Avoid spending CI resources and fix the issue of now executing CI tests on release PRs.
Current release PR:
- https://github.com/complytime/trestle-bot/pull/567
Jobs:
- https://github.com/complytime/trestle-bot/actions/workflows/release.yml

ci: CPLYTM-820 CPLYTM-821 - ensure release pr is triggered manually

---

scripts/get_rule_impacted_files.py

This module is designed to get the controls and profiles that are impacted by
the updated rule. It is useful to determine how to sync the updated rule
to OSCAL component-definition.
When filtering the control file, like `controls/cis_ocp_1_4_0/section-1.yml`, the `control` or `policy_id` should be "cis_ocp_1_4_0" for the product ocp4. 
`python get_rule_impacted_files.py rhel8 "/Users/huiwang/huiwang-fork/cac-content" file_permissions_kube_apiserver control
`

chore: update the ocp4 control name

---

tests/trestlebot/cli/test_sync_cac_content_cmd.py
trestlebot/tasks/sync_cac_content_task.py
trestlebot/transformers/cac_transformer.py

Add numerical suffix to component definition "Parameter" props
Closes CPLYTM-798
Regenerate Component Definition using `sync-cac-content component-definition` command , check props field.

fix: CPLYTM-798 Add numerical suffix to component definition "Parameter" props

---

.github/actions/setup-poetry/action.yml
.github/workflows/ci.yml
.github/workflows/codecov.yml
.github/workflows/conventional-title.yml
.github/workflows/mkdocs.yml
.github/workflows/publish.yml
.github/workflows/scorecard.yml
.github/workflows/validate-adrs.yml

Most of the commits are only standardizing versions in comments so they are also updated in dependabot PRs and consequently easier to review.
Some versions were updated in alignment to the last released version.
- CI using updated versions
- Easier to review future dependabot PRs
The commits are organized by modules.
- https://github.com/oxsecurity/megalinter/releases
- https://github.com/SonarSource/sonarqube-scan-action/releases
- https://github.com/actions/setup-python/releases
- https://github.com/docker/login-action/releases

ci(deps): update versions used in GH actions

---

scripts/init_rh_products_content.sh

This script initializes RHEL products OSCAL content using the Trestlebot CLI.
CPLYTM-744
Pre-requirements:
1. Git clone the Trestlebot and setup the trestlebot
2. Git clone CAC repository
3. Git clone OSCAL content reppository
4. Setup the OSCAL content branch
Requirements:
1. Local path to the CAC repository
2. Local path to the OSCAL repository
3. OSCAL repository branch containing the initial updates
How to run it:
1. Go to trestlebot repo directory:
2. Run `# sh scripts/init_rh_products_content.sh "/Users/huiwang/issue-743/content" "/Users/huiwang/issue-744/oscal-content" init_rh_products_content`
3. Go to oscal-content repo directory to check the results about the generated oscal content

chore: CPLYTM-744 add script for init rh products oscal content

---

.github/workflows/codecov.yml

Update workflow sonar projectKey parameter due to rename
SonarCloud check running as expected.

fix: Update workflow sonar projectKey parameter due to rename

---

complyscribe/transformers/cac_transformer.py

Load CaC content product_properties dir when processing rule. Some rule file needs Jinja2 macros value from [product_properties](https://github.com/ComplianceAsCode/content/tree/master/product_properties) dir.
Replace constructor with literal is to fix sonar scan fail, https://sonarcloud.io/organizations/rh-psce/rules?open=python%3AS7498&rule_key=python%3AS7498 
Closes CPLYTM-838
Try to generate OSCAL component-definition for rhel8-stig_rhel8-$levels . For example, generate component-definition for `rhel8-stig_rhel8-low`
```shell
poetry run trestlebot sync-cac-content catalog --cac-content-root ~/content --cac-policy-id stig_rhel8 --repo-path ~/trestlebot-workspace --oscal-catalog stig_rhel8 --branch main --committer-name test --committer-email test@redhat.com --dry-run
poetry run …
```

fix: CPLYTM-838 Load CaC content product_properties dir when processing rule

---

scripts/squash.sh

The CI sync content between CAC and OSCAL CI will call this script.
The CI of sync content between CAC and OSCAL will run `complyscribe` many times.
The auto-generated PRs of CAC and OSCAL content repos include multiple commits.
This script uses `git rebase -i` and automates squashing the latest N Git commits into a single one.
It automatically keeps the oldest commit's message and pushes the result.
Usage:
sh squash.sh $number_of_commits_to_squash

chore: [CPLYTM-884] add squash multiple commits script

---

complyscribe/tasks/sync_oscal_content_cd_task.py
complyscribe/tasks/sync_oscal_content_profile_task.py
complyscribe/utils.py
tests/complyscribe/cli/test_sync_oscal_content_cmd.py

Load all controls from OSCAL catalog when sync Component Definition to CaC.
None
- Load all controls from OSCAL catalog when sync Component Definition to CaC. Prevent we can not get OSCAL control id and CaC control id mapping for controls removed from OSCAL profile.
- Generate OSCAL catalog, profile and component definition with CaC content `products/rhel8/profiles/cis_server_l1.profile` . 
- Remove one control(e.g. `reload_dconf_db`) from OSCAL profile(e.g. `profiles/rhel8-cis_rhel8-l1_server/profile.json` ).
- Modify some control in OSCAL component definition(e.g. `reload_dconf_db`).
- Run 
```shell
poetry run complyscribe sync-oscal-content component-definition --dry-run --repo-path ~/trestlebot-workspace --committer-email axuan@redhat.com --committer-name axuan --branch master …
```

fix: Load all controls from OSCAL catalog when sync OSCL CD to CaC

---

complyscribe/const.py
complyscribe/transformers/cac_transformer.py
scripts/init_rh_products_content.sh

Some rules can't be loaded when I run the CLI sync-cac-content to transfer some OCP4 content to component-definition. The rules that can't be loaded are located in the same_guide_directory, `content/linux_os/guide`, not in the benchmark root `content/applications`.
This PR extends the benchmark root for ocp4 product to fix this error. 
- _Closes # [CPLYTM-882](https://issues.redhat.com/browse/CPLYTM-882)
How to test:
- Make sure you have already generated the related catalog and profile
- Generate the component-definition
`poetry run complyscribe sync-cac-content component-definition --repo-path /Users/huiwang/issue-810/oscal-content --committer-email test@redhat.com --committer-name test --branch test_transfer_cli5 --cac-content-root /Users/huiwang/content --product ocp4 --branch …

fix: [CPLYTM-894] expend the benchmark root for ocp4

---

tests/integration/README.md
tests/integration/conftest.py
tests/integration/test_int.py

Due to `complytime` executable rename to `complyctl`, integration test failed. Rename `complytime` to `complyctl` for integration test.
None
- Rename complytime to complyctl for integration test

fix: Fix integration test failure

---

docs/tutorials/sync-cac-content.md
docs/tutorials/sync-oscal-content.md

Update documentations. Add real world example for `sync-cac-content `commands.
- Closes CPLYTM-896
- Add real world example for `sync-cac-content `commands. Help users to understand how to use the projects, explain parameters may cause confusing.
- Update doc for `sync-oscal-content` commands.

docs: CPLYTM-896 Update documentations

---

complyscribe/tasks/sync_cac_catalog_task.py
complyscribe/utils.py
poetry.lock
pyproject.toml
tests/complyscribe/cli/test_sync_cac_content_cmd.py
tests/complyscribe/cli/test_sync_oscal_content_cmd.py
tests/data/json/rhel8.json
tests/testutils.py

Update ssg version to lastest, adjust test according to ssg change.
- Closes CPLYTM-916
- Update ssg version to latest
- Adjust tests due to ssg function result change. For example, using https://github.com/complytime/complyscribe/tree/main/tests/data/content_dir as content dir, code as below get `rhel8 example profile` variable result changed from `{'var_sshd_set_keepalive': {'rhel8': {'example': '1'}}, 'var_system_crypto_policy': {'rhel8': {'example': 'fips'}}}` to  `{'var_password_pam_minlen': {'rhel8': {'example': '1'}}, 'var_sshd_set_keepalive': {'rhel8': {'example': '1'}}, 'var_system_crypto_policy': {'rhel8': {'example': 'fips'}}}`
```python
from ssg.profiles import get_profiles_from_products
from ssg.variables import (
get_variables_from_profiles,
)
from typing import Dict, Any …
```

chore: Update ssg version, adjust test according to ssg change
