- .github/actions/setup-poetry/action.yml
- .github/workflows/ci.yml
Update poetry install to composite action
https://github.com/jpower432/trestle-bot/actions/runs/5324310460
> chore: creates composite action with full poetry setup

- .github/actions/setup-poetry/action.yml
Remove extra action step that installs dependencies 
https://github.com/jpower432/trestle-bot/actions/runs/5326712756
> fix: remove additional action step for dependency install

- docs/diagrams/assemble/assemble_diagrams.md
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes: https://issues.redhat.com/browse/PSCE-170
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
- Hardware:
- Toolchain:
- SDK:
> adds drawings

- trestlebot/cli.py
Fixes bug in pre-task execution in cli.py
Manually verified
> fix: fixes errors in pre-task execution in cli.py

- tests/trestlebot/tasks/authored/test_ssp.py
- tests/trestlebot/test_bot.py
- tests/trestlebot/test_cli.py
- trestlebot/cli.py
Adds unit tests for cli.py
Tests for fix in #11 
N/A
> test: adds cli.py testing to test invalid arg responses

- action.yml
- entrypoint.sh
- trestlebot/bot.py
- trestlebot/cli.py
Adds fixes after testing with GitHub Actions
https://github.com/afflom/improved-fishstick/actions/runs/5406175552/jobs/9822732569
> feat: add fixes for GitHub Actions integration

- TROUBLESHOOTING.md
Troubleshooting docs update
N/A
> chore: adds correction on how to setup auth for git with user token

- tests/trestlebot/test_bot.py
Fixes unit test error for PR #25
> test: adds test for custom PR title and fixes test for default value

- .github/workflows/publish.yml
Refs: PSCE-199
Adds workflow to publish image to be used outside of GH Actions
Related #29
> PSCE-199 feat: adds workflow to publish container image to GHCR

- README.md
**DOCS ONLY**
Add information about Action Behavior in the README.md along with the example yaml snippets.
N/A
> docs: adds action behavior information to README

- Dockerfile
- poetry.lock
- pyproject.toml
- tests/testutils.py
- tests/trestlebot/tasks/authored/test_ssp.py
- tests/trestlebot/test_gitlab.py
- trestlebot/bot.py
- trestlebot/const.py
- trestlebot/gitlab.py
- trestlebot/tasks/authored/ssp.py
Add create method on `AuthoredSSP` class to generate new system security plans with inheritance view
- Regression
> PSCE-194 - Add create method to generate new system security plans with inheritance view

- poetry.lock
Update certifi package
Deps update
N/A
> build(deps): updates certifi to 2023.07.22

- poetry.lock
- pyproject.toml
Pin compliance-trestle to a commit
> chore: update poetry lock

- tests/data/json/simplified_filter_profile.json
- tests/data/json/test_comp_2.json
- tests/testutils.py
- tests/trestlebot/tasks/authored/test_ssp.py
- tests/trestlebot/tasks/test_assemble_task.py
- tests/trestlebot/tasks/test_regenerate_task .py
- trestlebot/tasks/authored/ssp.py
> PSCE-202 - Adds create utility function to create ssps with ssp-filter

- tests/__init__.py
- tests/trestlebot/__init__.py
- tests/trestlebot/tasks/__init__.py
- tests/trestlebot/tasks/authored/__init__.py
- trestlebot/__init__.py
- trestlebot/tasks/__init__.py
- trestlebot/tasks/authored/__init__.py
Add package level descriptions
N/A
> docs: add package documentation to each init file

- README.md
Updates README warning to be more precise is the project development stage
N/A
> docs: update readme warning

- Dockerfile
- poetry.lock
- pyproject.toml
Updates the base images to ubi minimal
> chore: updates the base images to UBI minimal

- .github/workflows/publish.yml
Updates strategy for building release images to allow us to use GitHub Actions cache for cache management.
> build: updates image building strategy to use GHA cache

- trestlebot/transformers/yaml_transformer.py
Fixes type hinting issues in `yaml_transformer.py`.
N/A
> fix: fixes type hints and simplifies ToRules yaml transformer

- tests/conftest.py
- tests/e2e/README.md
- tests/e2e/test_e2e_compdef.py
- tests/e2e/test_e2e_ssp.py
- tests/testutils.py
- tests/trestlebot/tasks/authored/test_ssp.py
- tests/workflows/test_rules_transform_workflow.py
- trestlebot/tasks/authored/ssp.py
Adds end to end tests for SSP creation and autosync operations
> test: adds end to end tests for SSP creation and autosync

- tests/trestlebot/entrypoints/test_autosync.py
- trestlebot/entrypoints/autosync.py
- trestlebot/entrypoints/create_cd.py
- trestlebot/entrypoints/entrypoint_base.py
- trestlebot/entrypoints/rule_transform.py
- trestlebot/tasks/authored/base_authored.py
- Create a custom exception for input validation issues in entrypoint classes
- Updates entrypoint class `run` functions with try/except blocks with exception/exit handling using the `handle_exception` function.
- Add check for existence of trestle_root directory (separate commit)
Stacked/Incorporates #98 in response to feedback. 
- https://github.com/jpower432/trestle-bot/actions/runs/7186479037
- https://github.com/jpower432/cautious-potato/actions/runs/7186522609/job/19572095854 (`with GitHub Actions`)
> refactor: streamlines exit exception handling

- README.md
Adds badges to README.md for quick information about repository and the status
N/A
> docs: adds badges to README.md

- README.md
Updates badges to correctly reference the links.
N/A
> docs: fixes links in badges on README.md

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
Adds E2E tests for pull requests.
Once #140 is merged, the time to build the image will reduce significantly. Running E2E tests during the pull request process is more feasible.
Stacked with #140
> chore: adds E2E tests to ci.yml

- Dockerfile
- Upgrade setuptools and pip globally and in the virtual env.
- Remove unused POETRY_HOME env.
> chore(deps): updates Dockerfile to upgrade setuptools during build

- trestlebot/bot.py
Grammar and spelling fixes on comments on `bot.py`
N/A
> fix: fixes typos in the TrestleBot class in bot.py

- README.md
- actions/sync-upstreams/README.md
- actions/sync-upstreams/action.yml
- tests/e2e/test_e2e_compdef.py
- tests/workflows/test_rules_transform_workflow.py
The `sync-upstreams` information was missing from the top level `README.md` and the description on the include_model_names and exclude_model_names was a misleading.
N/A
> docs: updates README.md and sync-upstreams README.md

- README.md
Update README with information about available commands
N/A
> docs: updates README for create-ssp

- README.md
Updates typos created from #167
> docs: fixes typos in the README.md file

- poetry.lock
- pyproject.toml
Updates `compliance-trestle` to 2.5.1
N/A. Updates from 2.5.0 to 2.5.1.
> chore(deps): updates compliance-trestle to 2.5.1

- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/trestlebot/transformers/test_csv_transformer.py
- trestlebot/transformers/csv_transformer.py
This updates compliance-trestle dependency to use the latest commit on `develop` and updates the CSVBuilder class to adapt to changes. This will be in draft until the next trestle release.
> chore: updates CSVBuilder to handle updates to the compliance-trestle CSVColumns class

- actions/autosync/README.md
- actions/autosync/action.yml
- actions/create-cd/README.md
- actions/create-cd/action.yml
- actions/rules-transform/README.md
- actions/rules-transform/action.yml
- actions/sync-upstreams/README.md
- actions/sync-upstreams/action.yml
Updates action documented for more precise descriptions of inputs. Related to #185.
N/A
> chore: updates descriptions on actions inputs to be more precise

- actions/autosync/README.md
- actions/autosync/action.yml
- actions/autosync/auto-sync-entrypoint.sh
- tests/trestlebot/entrypoints/test_autosync.py
- trestlebot/entrypoints/autosync.py
> feat: adds version flag to autosync command for assembly task

- .github/actions/publish-image/action.yml
- .github/workflows/publish.yml
The schedule trigger is added to rebuild images for
base image updates and `semver` tags are introduced to continuous updates
- Toolchain: `act`, `podman`
> ci: updates publish.yml image releasing process

- poetry.lock
- pyproject.toml
Dependency update for `compliance-trestle-fedramp`
N/A
> build(deps): bumps compliance-trestle-fedramp to 0.4.0

- README.md
Add a notice in README to inform users of the GitHub org change.
> docs: add notice regarding repo org move

- tests/trestlebot/cli/test_sync_cac_content_cmd.py
- trestlebot/transformers/cac_transformer.py
Add unit test for validation component and fix the Rule and Check mapping from Property. 
Add test to cover it and tested locally.
> feat: add unit test for validation component

- trestlebot/transformers/cac_transformer.py
The validation component is only based on the rules. This PR is to add parameter mapping.
Tested locally with the mock data that has Parameters.
> fix: improve the validation components with parameters

- poetry.lock
- tests/data/content_dir/shared/macros/01-general.jinja
- tests/data/content_dir/shared/macros/10-ansible.jinja
- tests/data/content_dir/shared/macros/10-bash.jinja
- tests/data/content_dir/shared/macros/10-fixtext.jinja
- tests/data/content_dir/shared/macros/10-ignition.jinja
- tests/data/content_dir/shared/macros/10-kubernetes.jinja
- tests/data/content_dir/shared/macros/10-ocil.jinja
- tests/data/content_dir/shared/macros/10-oval.jinja
- tests/data/content_dir/shared/macros/10-srg_requirement.jinja
- tests/data/content_dir/shared/macros/10-warning.jinja
- tests/data/content_dir/shared/macros/20-rules.jinja
- tests/data/content_dir/shared/macros/20-test-scenarios.jinja
- tests/trestlebot/cli/test_sync_cac_content_cmd.py
- trestlebot/tasks/sync_cac_content_task.py
- trestlebot/transformers/cac_transformer.py
> feat: CPLYTM-390 add parameter transformation

- trestlebot/transformers/cac_transformer.py
Update rule description with rule title
> feat: update rule description value with rule title

- tests/trestlebot/cli/test_sync_cac_content_cmd.py
- trestlebot/tasks/sync_cac_content_task.py
> feat: CPLYTM-429 populate control notes into implemented requirement

- tests/trestlebot/tasks/authored/test_profile.py
- trestlebot/tasks/authored/profile.py
- trestlebot/tasks/sync_cac_content_profile_task.py
- trestlebot/tasks/sync_cac_content_task.py
This is a follow-up update based on a comment here: https://github.com/complytime/trestle-bot/pull/431#discussion_r1925667310
> chore: merge control resolvers from different modules

- .gitignore
- README.md
- docs/tutorials/sync-cac-content.md
- tests/trestlebot/cli/test_sync_cac_content_cmd.py
- trestlebot/cli/commands/sync_cac_content.py
- trestlebot/cli/root.py
Group sync-cac-content and sync-cac-content-profile cmd, update related docs and tests
Before group:
After group:
no issue related
- Hardware:
- Toolchain:
- SDK:
> chore: Group sync-cac-content and sync-cac-content-profile cmd, update related docs and tests

- CONTRIBUTING.md
- docs/index.md
- docs/tutorials/authoring.md
No tests, only doc update
- Hardware:
- Toolchain:
- SDK:
> chore: CPLYTM-441 update docs

- scripts/get-github-release.sh
This script is for getting complytime releases to support unit tests
> CPLYTM-539: chore: add get-github-release.sh script

- README.md
- docs/tutorials/sync-oscal-content.md
- tests/data/json/rhel8.json
- tests/testutils.py
- tests/trestlebot/cli/test_sync_oscal_content_cmd.py
- trestlebot/tasks/sync_oscal_content_task.py
Implemented validate and sync rule function for sync-oscal-content cac-control command
Sample cmd:
```shell
poetry run trestlebot sync-oscal-content cac-control --branch main --cac-content-root ~/content --committer-name axuan --committer-email axuan@redhat.com --dry-run --repo-path ~/trestlebot-workspace --product ocp4
```
Fixes CPLYTM-543, CPLYTM-540
- Hardware:
- Toolchain:
- SDK:
> feat: Implemented validate and sync rule function for sync-oscal-content command

- README.md
- trestlebot/cli/root.py
Remove duplicate catalog cmd. 
Fixes CPLYTM-686
- Hardware:
- Toolchain:
- SDK:
> chore: CPLYTM-686 Remove duplicate catalog cmd

- docs/tutorials/sync-cac-content.md
- tests/trestlebot/cli/test_sync_cac_content_cmd.py
- trestlebot/cli/commands/sync_cac_content.py
rename --policy-id by --cac-policy-id to make it more intuitive
- Hardware:
- Toolchain:
- SDK:
> chore: CPLYTM-687 rename --policy-id by --cac-policy-id to make it more intuitive

- docs/tutorials/sync-oscal-content.md
- tests/data/json/rhel8.json
- tests/trestlebot/cli/test_sync_oscal_content_cmd.py
- trestlebot/tasks/sync_oscal_content_task.py
Syns OSCAL Component Definition control-implementation status to Cac control file control status. 
- Hardware:
- Toolchain:
- SDK:
> feat: CPLYTM-661, CPLYTM-662 sync OSCAL control status to cac control status

- CONTRIBUTING.md
- tests/integration/README.md
Add integration test dev docs
n/a
> chore: add integration test dev docs

- docs/tutorials/sync-cac-content.md
This PR updates documentation associated in the `sync_cac_content.md` tutorial. The updates are coupled with the changes made in PR #532. 
Depends on #532 
- Firmware version: N40ET47W (1.29 )
- Toolchain:
- SDK:
> docs: CPLYTM-709 update reference to component definition location

- docs/tutorials/sync-oscal-content.md
- tests/testutils.py
- tests/trestlebot/cli/test_sync_oscal_content_cmd.py
- trestlebot/cli/commands/sync_oscal_content.py
- trestlebot/tasks/sync_oscal_content_cd_task.py
Update sync-oscal-content component-definition command to adapt OSCAL CD directory change , context #532  . 
Fixes CPLYTM-732
- Hardware:
- Toolchain:
- SDK:
> refactor: CPLYTM-732 update sync-oscal-content command to adapt OSCAL CD directory change

- trestlebot/tasks/sync_oscal_content_cd_task.py
- trestlebot/utils.py
Fix a corner case when sync OSCAL component definition to CaC. For CaC control file, if `rules` field is empty and there is comments under `rules` field, there will be yaml file format error after modification. Resolution is move old comments above rules field.
- Hardware:
- Toolchain:
- SDK:
> fix: yaml format error when sync OSCAL cd to CaC

- docs/tutorials/sync-oscal-content.md
This PR is for a quick fix in documentation that was noticed during testing of PR #537.  
- Firmware version: N40ET47W (1.29 )
- Toolchain:
- SDK:
> fix: updating reference to profile in tutorial

- trestlebot/tasks/sync_oscal_content_cd_task.py
Bug fix. When sync OSCAL to CaC. If OSCAL set-parameters filed is None, set to empty list. 
- Hardware:
- Toolchain:
- SDK:
> fix: If OSCAL set-parameters filed is None, set to empty list

- docs/tutorials/sync-oscal-content.md
- tests/data/json/rhel8.json
- tests/testutils.py
- tests/trestlebot/cli/test_sync_oscal_content_cmd.py
- trestlebot/tasks/sync_cac_content_task.py
- trestlebot/tasks/sync_oscal_content_cd_task.py
- trestlebot/utils.py
Sync OSCAL component definition statements to CaC notes
Modify some control's statements field in OSCAL component definition, then run 
`poetry run trestlebot sync-oscal-content component-definition --product ocp4 --oscal-profile nist_ocp4-high --cac-content-root ~/content --repo-path ~/trestlebot-workspace --committer-name test --committer-email test@redhat.com --branch main --dry-run` cmd , after that check corresponding control file change on CaC side.
- Hardware:
- Toolchain:
- SDK:
> feat: CPLYTM-711 CPLYTM-712 Sync OSCAL component definition statements to CaC notes

- tests/integration/conftest.py
- tests/integration/test_int.py
Complytime looks for data in different directories now, so this updates them
- Hardware:
- Toolchain:
- SDK:
> chore: update integration test paths

- tests/trestlebot/cli/test_sync_cac_catalog_task.py
> chore: add tests

- .github/dependabot.yml
- .github/workflows/dependabot-auto-review.yml
- .github/workflows/dependencies.yml
This PR:
- introduces workflow to support dependabot reviews
- introduces workflow to check dependencies
- refine dependabot settings
This should help us to maintain repository dependencies with lower cost.
Something similar is already implemented in [complytime](https://github.com/complytime/complytime/tree/main/.github).
> chore: dependabot settings and auto review process

- .github/workflows/dependabot-auto-review.yml
Fix JS syntax to include label.
These labels can help us triagging dependabot PRs.
- https://github.com/complytime/trestle-bot/actions/runs/15486091806/job/43601001224?pr=587
> ci: fix JS syntax to include label

- sonar-project.properties
Update sonar projectKey due to rename
None
SonarCloud check running as expected.
> fix: Update sonar projectKey

- complyscribe/transformers/yaml_transformer.py
- pyproject.toml
- tests/complyscribe/cli/test_sync_cac_content_cmd.py
- tests/integration/test_int.py
_The PR fixes some warnings raised during testing._
> fix: fix several deprecated warnings
